# Generated by Django 4.0.4 on 2022-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_want', models.BooleanField(default=True, verbose_name='是否是一个需求帖')),
                ('want', models.CharField(max_length=200, verbose_name='想换到的物品描述、数量')),
                ('offer', models.CharField(max_length=200, verbose_name='可以用于交换的物品描述、数量')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
